sudo: required
dist: trusty
language: cpp
compiler: clang
addons:
    apt:
        packages:
            - cmake
            - libzmq3
            - libzmq3-dev
            - libzmqpp3
            - libzmqpp-dev
            - libjson-c-dev
before_install:
    - cd drakvuf
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/usr/local/lib
    - sudo add-apt-repository "deb mirror://mirrors.ubuntu.com/mirrors.txt trusty main restricted universe multiverse" -y
    - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32
    - sudo apt-get update -qq
    - sudo apt-get install -y bison flex check libjson-c-dev uuid-dev libstdc++-4.8-dev
    - sudo apt-get build-dep libxen-dev
    - sudo dpkg -i test-packages/xentools_4.7-drakvuf1-1_amd64.deb
    - sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.so /usr/lib/x86_64-linux-gnu/libstdc++.so
    - cd libvmi && ./autogen.sh && ./configure --enable-xen --without-xenstore
    - make && sudo make install
script:
    - cd ../.. && mkdir build && cd build
    - cmake ..
    - make
os:
    - linux
